### ISSUE TITLE
Remove suggestion of using lambdas in model field arguments (incompatible with migrations) 

### ISSUE THREAD

**Issue by Jskarie** [saulshanabrook/django-simpleimages#26]
I think this bug describes the issue better then I can.
https://code.djangoproject.com/ticket/22351

Creating the migration failed in Django 1.7, unless I commented out the lambda function.

I appreciate the work you've done for this extension.

**Comment by saulshanabrook** [comment]
@Jskarie Oh yeah good point. I did this in my local codebase when I just moved to Django 1.9 and forgot to update the docs here. I will update them now.
